/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DataStructures.DynamicArray;
import hotelbookingsystem.Hotel;
import hotelbookingsystem.RoomHistory;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Santiago
 */
public class History extends javax.swing.JFrame {
    Hotel hotel = Hotel.getInstance();    
    
    /**
     * Creates new form History
     */
    public History() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrameA = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        RoomIDInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        logohistory = new javax.swing.JLabel();
        barhistory = new javax.swing.JPanel();
        bartxt = new javax.swing.JLabel();
        searchbtnh = new javax.swing.JPanel();
        searchtxth = new javax.swing.JLabel();
        backbtnh = new javax.swing.JPanel();
        backtxth = new javax.swing.JLabel();
        RoomIDInput1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JFrameA.setBackground(new java.awt.Color(255, 255, 255));
        JFrameA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JFrameA.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("SEARCH: ");
        JFrameA.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 60));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        JFrameA.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 220, -1));

        RoomIDInput.setBackground(new java.awt.Color(255, 255, 255));
        RoomIDInput.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        RoomIDInput.setForeground(new java.awt.Color(0, 0, 0));
        RoomIDInput.setText("Enter the room id");
        RoomIDInput.setBorder(null);
        RoomIDInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomIDInputMouseClicked(evt);
            }
        });
        RoomIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomIDInputActionPerformed(evt);
            }
        });
        JFrameA.add(RoomIDInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 20));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        JFrameA.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 510, 220));

        logohistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGOOO.png"))); // NOI18N
        logohistory.setText(" ");
        JFrameA.add(logohistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 140));

        barhistory.setBackground(new java.awt.Color(0, 67, 67));

        bartxt.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        bartxt.setForeground(new java.awt.Color(255, 255, 255));
        bartxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bartxt.setText("HISTORY");

        javax.swing.GroupLayout barhistoryLayout = new javax.swing.GroupLayout(barhistory);
        barhistory.setLayout(barhistoryLayout);
        barhistoryLayout.setHorizontalGroup(
            barhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        barhistoryLayout.setVerticalGroup(
            barhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        JFrameA.add(barhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 140));

        searchbtnh.setBackground(new java.awt.Color(0, 67, 67));

        searchtxth.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        searchtxth.setForeground(new java.awt.Color(255, 255, 255));
        searchtxth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchtxth.setText("SEARCH");
        searchtxth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchtxth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchtxthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchtxthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchtxthMouseExited(evt);
            }
        });

        javax.swing.GroupLayout searchbtnhLayout = new javax.swing.GroupLayout(searchbtnh);
        searchbtnh.setLayout(searchbtnhLayout);
        searchbtnhLayout.setHorizontalGroup(
            searchbtnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchtxth, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        searchbtnhLayout.setVerticalGroup(
            searchbtnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchtxth, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        JFrameA.add(searchbtnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 130, 40));

        backbtnh.setBackground(new java.awt.Color(0, 67, 67));
        backbtnh.setForeground(new java.awt.Color(255, 255, 255));

        backtxth.setBackground(new java.awt.Color(255, 255, 255));
        backtxth.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        backtxth.setForeground(new java.awt.Color(255, 255, 255));
        backtxth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backtxth.setText("BACK");
        backtxth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtxth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtxthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backtxthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backtxthMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backbtnhLayout = new javax.swing.GroupLayout(backbtnh);
        backbtnh.setLayout(backbtnhLayout);
        backbtnhLayout.setHorizontalGroup(
            backbtnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backtxth, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        backbtnhLayout.setVerticalGroup(
            backbtnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backtxth, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        JFrameA.add(backbtnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 130, 40));

        RoomIDInput1.setBackground(new java.awt.Color(255, 255, 255));
        RoomIDInput1.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        RoomIDInput1.setForeground(new java.awt.Color(0, 0, 0));
        RoomIDInput1.setBorder(null);
        RoomIDInput1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomIDInput1MouseClicked(evt);
            }
        });
        RoomIDInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomIDInput1ActionPerformed(evt);
            }
        });
        JFrameA.add(RoomIDInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 0, 10));

        getContentPane().add(JFrameA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RoomIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomIDInputActionPerformed

    private void backtxthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtxthMouseEntered
        backbtnh.setBackground(new Color(0,160,133));
    }//GEN-LAST:event_backtxthMouseEntered

    private void backtxthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtxthMouseExited
        backbtnh.setBackground(new Color(0,67,67));
    }//GEN-LAST:event_backtxthMouseExited

    private void searchtxthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtxthMouseEntered
        searchbtnh.setBackground(new Color(0,160,133));
    }//GEN-LAST:event_searchtxthMouseEntered

    private void backtxthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtxthMouseClicked
        this.setVisible(false); 
        jTextArea1.setText("");
        RoomIDInput.setText("Enter the room id");
    }//GEN-LAST:event_backtxthMouseClicked

    private void searchtxthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtxthMouseExited
        searchbtnh.setBackground(new Color(0,67,67));
    }//GEN-LAST:event_searchtxthMouseExited

    private void RoomIDInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomIDInputMouseClicked
        RoomIDInput.setText("");
    }//GEN-LAST:event_RoomIDInputMouseClicked

    private void RoomIDInput1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomIDInput1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomIDInput1MouseClicked

    private void RoomIDInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomIDInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomIDInput1ActionPerformed

    private void searchtxthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtxthMouseClicked
        if (RoomIDInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a room ID.");
        } else {
            try {
                int roomID = Integer.parseInt(RoomIDInput.getText().trim());
                DynamicArray<RoomHistory> a = null;
                if (hotel.searchHistoryByRoom(roomID) != null) {
                    a = (DynamicArray) hotel.searchHistoryByRoom(roomID).getData();
                }
                if (a == null || a.size() == 0) {
                    JOptionPane.showMessageDialog(null, "No history found for this room ID.");
                } else {
                    jTextArea1.setText("Room: "+RoomIDInput.getText()+"\n");
                    for (RoomHistory p : a) {
                        jTextArea1.append("ID: "+p.getID()+" | Name: "+p.getName()+" | Last Name: "+p.getLastName()+"\n");
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid room ID. Please enter a numeric value.");
            }
        }
    }//GEN-LAST:event_searchtxthMouseClicked

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        
        
    }//GEN-LAST:event_jTextArea1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JFrameA;
    private javax.swing.JTextField RoomIDInput;
    private javax.swing.JTextField RoomIDInput1;
    private javax.swing.JPanel backbtnh;
    private javax.swing.JLabel backtxth;
    private javax.swing.JPanel barhistory;
    private javax.swing.JLabel bartxt;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logohistory;
    private javax.swing.JPanel searchbtnh;
    private javax.swing.JLabel searchtxth;
    // End of variables declaration//GEN-END:variables
}
