/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DataStructures.AVLNode;
import hotelbookingsystem.ClientReservation;
import hotelbookingsystem.Hotel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Santiago
 */
public class SearchRes extends javax.swing.JFrame {
    Hotel hotel = Hotel.getInstance();
    /**
     * Creates new form SearchRes
     */
    public SearchRes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgsr = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        bar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        srbackbtn = new javax.swing.JPanel();
        srbacktxt = new javax.swing.JLabel();
        searchsubt = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        gci = new javax.swing.JTextField();
        rsearchbtn = new javax.swing.JPanel();
        rsearchtxt = new javax.swing.JLabel();
        searchsubt1 = new javax.swing.JLabel();
        searchsubt2 = new javax.swing.JLabel();
        searchsubt3 = new javax.swing.JLabel();
        gci1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        searchsubt4 = new javax.swing.JLabel();
        searchsubt5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgsr.setBackground(new java.awt.Color(255, 255, 255));
        bgsr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGOOO.png"))); // NOI18N
        logo.setText(" ");
        bgsr.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        bar.setBackground(new java.awt.Color(0, 67, 67));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEARCH RESERVATION");

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        bgsr.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 140));

        srbackbtn.setBackground(new java.awt.Color(0, 67, 67));

        srbacktxt.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        srbacktxt.setForeground(new java.awt.Color(255, 255, 255));
        srbacktxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        srbacktxt.setText("BACK");
        srbacktxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        srbacktxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                srbacktxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                srbacktxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                srbacktxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout srbackbtnLayout = new javax.swing.GroupLayout(srbackbtn);
        srbackbtn.setLayout(srbackbtnLayout);
        srbackbtnLayout.setHorizontalGroup(
            srbackbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srbacktxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        srbackbtnLayout.setVerticalGroup(
            srbackbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srbacktxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bgsr.add(srbackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 130, 40));

        searchsubt.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        searchsubt.setForeground(new java.awt.Color(0, 102, 102));
        bgsr.add(searchsubt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 10));

        separator.setForeground(new java.awt.Color(0, 0, 0));
        bgsr.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 10));

        gci.setBackground(new java.awt.Color(255, 255, 255));
        gci.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        gci.setForeground(new java.awt.Color(0, 0, 0));
        gci.setText("Enter the id/ci");
        gci.setBorder(null);
        gci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gciMouseClicked(evt);
            }
        });
        gci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gciActionPerformed(evt);
            }
        });
        gci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gciKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gciKeyTyped(evt);
            }
        });
        bgsr.add(gci, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 240, 20));

        rsearchbtn.setBackground(new java.awt.Color(0, 67, 67));

        rsearchtxt.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        rsearchtxt.setForeground(new java.awt.Color(255, 255, 255));
        rsearchtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rsearchtxt.setText("SEARCH");
        rsearchtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rsearchtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rsearchtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rsearchtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rsearchtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout rsearchbtnLayout = new javax.swing.GroupLayout(rsearchbtn);
        rsearchbtn.setLayout(rsearchbtnLayout);
        rsearchbtnLayout.setHorizontalGroup(
            rsearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rsearchtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        rsearchbtnLayout.setVerticalGroup(
            rsearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rsearchtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bgsr.add(rsearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 130, 40));

        searchsubt1.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        searchsubt1.setForeground(new java.awt.Color(0, 102, 102));
        bgsr.add(searchsubt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 0, 10));

        searchsubt2.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        searchsubt2.setText("p");
        bgsr.add(searchsubt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 10, 10));

        searchsubt3.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        searchsubt3.setForeground(new java.awt.Color(0, 102, 102));
        searchsubt3.setText("when writing the ID/CI number");
        bgsr.add(searchsubt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 260, 30));

        gci1.setBackground(new java.awt.Color(255, 255, 255));
        gci1.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        gci1.setForeground(new java.awt.Color(0, 0, 0));
        gci1.setBorder(null);
        gci1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gci1MouseClicked(evt);
            }
        });
        gci1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gci1ActionPerformed(evt);
            }
        });
        gci1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gci1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gci1KeyTyped(evt);
            }
        });
        bgsr.add(gci1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 10, 10));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        bgsr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 500, 220));

        searchsubt4.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        searchsubt4.setForeground(new java.awt.Color(0, 102, 102));
        searchsubt4.setText("SEARCH:");
        bgsr.add(searchsubt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        searchsubt5.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        searchsubt5.setForeground(new java.awt.Color(0, 102, 102));
        searchsubt5.setText("Do not include the periods ");
        bgsr.add(searchsubt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 220, 40));

        getContentPane().add(bgsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srbacktxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srbacktxtMouseEntered
        srbackbtn.setBackground(new Color(0,160,133));
    }//GEN-LAST:event_srbacktxtMouseEntered

    private void srbacktxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srbacktxtMouseExited
        srbackbtn.setBackground(new Color(0,67,67));
    }//GEN-LAST:event_srbacktxtMouseExited

    private void srbacktxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srbacktxtMouseClicked
        this.setVisible(false); 
        gci.setText("Enter the id/ci");
        jTextArea1.setText("");
    }//GEN-LAST:event_srbacktxtMouseClicked

    private void gciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gciMouseClicked
        gci.setText("");
    }//GEN-LAST:event_gciMouseClicked

    private void gciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gciActionPerformed

    private void gciKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gciKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gciKeyPressed

    private void gciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gciKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gciKeyTyped

    private void rsearchtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsearchtxtMouseEntered
        rsearchbtn.setBackground(new Color(0,160,133));
    }//GEN-LAST:event_rsearchtxtMouseEntered

    private void rsearchtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsearchtxtMouseExited
        rsearchbtn.setBackground(new Color(0,67,67));
    }//GEN-LAST:event_rsearchtxtMouseExited

    private void gci1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gci1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gci1MouseClicked

    private void gci1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gci1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gci1ActionPerformed

    private void gci1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gci1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gci1KeyPressed

    private void gci1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gci1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gci1KeyTyped

    private void rsearchtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsearchtxtMouseClicked
        String idText = gci.getText().trim();
        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter an id.");
        } else {
            try {
                int id = Integer.parseInt(idText);
                AVLNode<ClientReservation> node = hotel.searchReservationByCi(id);
                if (node != null) {
                    ClientReservation reservation = node.getData();
                    jTextArea1.setText(reservation.display());
                } else {
                    JOptionPane.showMessageDialog(null, "Reservation not found");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid id. Please enter a numeric value.");
            }
        }
    }//GEN-LAST:event_rsearchtxtMouseClicked

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked

    }//GEN-LAST:event_jTextArea1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bgsr;
    private javax.swing.JTextField gci;
    private javax.swing.JTextField gci1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel rsearchbtn;
    private javax.swing.JLabel rsearchtxt;
    private javax.swing.JLabel searchsubt;
    private javax.swing.JLabel searchsubt1;
    private javax.swing.JLabel searchsubt2;
    private javax.swing.JLabel searchsubt3;
    private javax.swing.JLabel searchsubt4;
    private javax.swing.JLabel searchsubt5;
    private javax.swing.JSeparator separator;
    private javax.swing.JPanel srbackbtn;
    private javax.swing.JLabel srbacktxt;
    // End of variables declaration//GEN-END:variables
}
